version: "3.1"
services:
    web:
        build: .
        ports:
            - "8001:80"
        depends_on:
            - db
        volumes:
            - ./plugins/ExternalContent:/var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/ExternalContent
            - ../miquiz-ilias:/var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/MIQuiz
            - ./config/customizing/page.xsl:/var/www/html/ilias/Services/COPage/xsl/page.xsl
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ilias
            MYSQL_USER: ilias
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./config/db:/etc/mysql/conf.d
            - ./config/startup_db.sql:/docker-entrypoint-initdb.d/dump.sql